export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { getUser } from '@/lib/db/queries.server';
import { logger } from '@/lib/logger';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';

/**
 * Simple, optimized document generator for CV content
 * Generates a DOCX file from the provided CV content with minimal processing
 */
export async function POST(request: NextRequest) {
  try {
    // Check authentication
    const user = await getUser();
    if (!user) {
      logger.warn('Unauthorized access attempt to generate-docx-simple API');
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }
    
    // Parse request body
    const body = await request.json();
    const { content, jobTitle = 'Position', cvId, metadata = {} } = body;
    
    if (!content) {
      logger.error('Missing content in generate-docx-simple request');
      return NextResponse.json(
        { success: false, error: 'Missing content' },
        { status: 400 }
      );
    }
    
    logger.info(`Generating simple document for job: ${jobTitle}`);
    
    // Fast-path document generation with minimal processing
    const doc = await createSimpleDocument(content, jobTitle);
    
    // Generate document buffer
    const buffer = await Packer.toBuffer(doc);
    
    // Return the generated document
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="CV_${jobTitle.replace(/[^a-zA-Z0-9]/g, '_')}.docx"`,
      },
    });
  } catch (error) {
    logger.error('Error in generate-docx-simple API:', error instanceof Error ? error.message : String(error));
    return NextResponse.json(
      { success: false, error: 'Failed to generate document' },
      { status: 500 }
    );
  }
}

/**
 * Create a simple document with minimal processing for better performance
 */
async function createSimpleDocument(content: string, jobTitle: string): Promise<Document> {
  // Split content into sections for faster processing
  const paragraphs = content.split('\n').map(line => {
    const trim = line.trim();
    
    // Skip empty lines
    if (!trim.length) {
      return new Paragraph({});
    }
    
    // Detect headings (simple heuristic)
    if (trim.toUpperCase() === trim && trim.length <= 30) {
      return new Paragraph({
        text: trim,
        heading: HeadingLevel.HEADING_1,
      });
    }
    
    // Regular paragraph
    return new Paragraph({
      children: [new TextRun({ text: trim })],
    });
  });
  
  // Add title
  paragraphs.unshift(new Paragraph({
    text: `Optimized CV for ${jobTitle}`,
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
  }));

  // Create document with all sections and content defined upfront
  const doc = new Document({
    title: `CV for ${jobTitle}`,
    description: 'Optimized CV generated by CV Optimizer',
    sections: [{
      properties: {},
      children: paragraphs,
    }],
    styles: {
      paragraphStyles: [
        {
          id: 'Normal',
          name: 'Normal',
          run: {
            font: 'Calibri',
            size: 24,
            color: '000000',
          },
          paragraph: {
            alignment: AlignmentType.LEFT,
            spacing: { line: 276 }, // Approximately 1.15 line spacing
          },
        },
        {
          id: 'Heading1',
          name: 'Heading 1',
          run: {
            font: 'Calibri',
            size: 32,
            bold: true,
            color: '000000',
          },
          paragraph: {
            alignment: AlignmentType.LEFT,
            spacing: { before: 240, after: 120 },
          },
        },
        {
          id: 'Heading2',
          name: 'Heading 2',
          run: {
            font: 'Calibri',
            size: 28,
            bold: true,
            color: '222222',
          },
          paragraph: {
            alignment: AlignmentType.LEFT,
            spacing: { before: 240, after: 120 },
          },
        },
      ],
    },
  });
  
  return doc;
} 